name: Dev Workflow - Test and check thing
on:
  push:
    branches:
      - client-instance-creation
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run tests
        run: |
          npm ci
          npm run test  
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CYCLIC_DB_NPM_TOKEN }}
          tag: "dev" 